load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "service",
    srcs = ["wheel.go"],
    importpath = "spinwheel/backend/internal/service",
    visibility = ["//backend:__subpackages__"],
    deps = [
        "//backend/internal/repository",
        "//backend/pkg/models",
    ],
)

go_test(
    name = "service_test",
    srcs = ["wheel_test.go"],
    embed = [":service"],
    deps = [
        "//backend/internal/repository",
        "//backend/pkg/models",
        "@com_github_google_uuid//:uuid",
    ],
)
